[common_attributes]

#Identifier used across further configuration calls.
common_attributes_config_id = common_attributes

#Represents the X x Y input. For example, 4 would represent an input size of 4 x 4
input_size = 91
image_size = 91
gaussian_range_start_x = -4
gaussian_range_end_x = 4
gaussian_range_start_y = -4
gaussian_range_end_y = 4
num_images = 4000

[baseline_experiment]

[parametric_experiment_1]
#Looking at how the FFN size affects performance.
fnn_architecture_np_linspace_start = 100
fnn_architecture_np_linspace_end = 1
fnn_architecture_np_linspace_num_layers = 5, 10, 15, 20
num_training_epochs = 50
num_training_rounds = 3
learning_rate = 0.01

[parametric_experiment_2]
# Looking at how the number of feature maps per layer affects performance.
experiment_name = parametric_experiment_2
cnn_output_feature_maps_start_ratio = 1
cnn_output_feature_maps_end_ratio = 11
num_parameters = 10
num_training_epochs = 50
learning_rate = 0.01

[parametric_experiment_2]
# Looking at how the kernel size per layer affects performance.
experiment_name = parametric_experiment_3
cnn_start_kernel_size = 3
cnn_end_kernel_size = 16
num_parameters = 12
num_training_epochs = 50
learning_rate = 0.01


